import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, ThinkingLevel } from "@google/genai";
import { buildGenerateMessagePrompt } from "@/lib/gemini-message-prompts";

const API_KEY = process.env.GEMINI_API_KEY;

if (!API_KEY) {
  throw new Error("GEMINI_API_KEY is not set in environment variables");
}

const genAI = new GoogleGenAI({});

export async function POST(req: NextRequest) {
  const body = await req.json();

  const prompt = buildGenerateMessagePrompt({
    occasion: body.occasion,
    headline: body.headline,
    sender: body.sender,
    recipient: body.recipient,
  });

  try {
    const response = await genAI.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        thinkingConfig: {
          thinkingLevel: ThinkingLevel.LOW,
        },
      },
    });
    const message = response.text;

    if (!message) {
      return NextResponse.json(
        { error: "No message generated by Gemini." },
        { status: 500 },
      );
    }

    return NextResponse.json({ message });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to generate message.", details: String(err) },
      { status: 500 },
    );
  }
}
