import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI, ThinkingLevel } from "@google/genai";

const API_KEY = process.env.GEMINI_API_KEY;

if (!API_KEY) {
  throw new Error("GEMINI_API_KEY is not set in environment variables");
}

const genAI = new GoogleGenAI({});

export async function POST(req: NextRequest) {
  const body = await req.json();

  const prompt = `Write a short, sweet, romantic, human ${body.occasion} message (4-7 sentences), written as if by a person to their partner. Make sure it is sincere and not cheesy, and does not sound like it was written by an AI.`;

  try {
    const response = await genAI.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        thinkingConfig: {
          thinkingLevel: ThinkingLevel.LOW,
        },
      },
    });
    const message = response.text;

    if (!message) {
      return NextResponse.json(
        { error: "No message generated by Gemini." },
        { status: 500 },
      );
    }

    return NextResponse.json({ message });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to generate message.", details: String(err) },
      { status: 500 },
    );
  }
}
